### ISSUE TITLE
Remote vs Local Site CSS

### ISSUE THREAD

**Issue by kitajchuk** [kitajchuk/node-squarespace-server#10]

**Comment by loadedsith** [comment]
I've been annoyed by this. Mostly when I change a rule I'm clearing the cache, but I wonder if you could simply inject an extra body class, say "sqs-local" then wrap all the local LESS code with that class. This should make every local rule more important than remote rules, without failing to load the remote css.

What do you think?

**Comment by kitajchuk** [comment]
Unfortunately, I don't think a specificity solution will fully resolve the pain points currently related to local css and remote css. The only real ideal resolve would be to manage to serve only remote Squarespace css without any of the template specific css. That way the local css is the only template css loading locally. Reading through some of this conversation, however, will reveal that more issues may arise therein: https://github.com/kitajchuk/node-squarespace-server/issues/94. For instance, the custom sqs imports cannot work locally.

**Comment by kitajchuk** [comment]
Closing this issue as there isn't a viable resolve. In addition, The magic sqs less imports will be ignored but logged locally and the styles will still come from the remote site.css anyway. This was worked out in a pull request with these commits:

df9604fcfb470d229f557b3f19edb36b9260d073
8f59e41d39bfba26d3d84a5a67fa561492908bbe
