### ISSUE TITLE
TemplateSyntaxError: Got too few {end} statements

### ISSUE THREAD

**Issue by kweestian** [kitajchuk/node-squarespace-server#100]
Hey first off thank for making this, really awesome!

Making a project for a friend, kind of a newbie at life/coding so bare with me

Everything was running fine yesterday, then I pushed some minor commits to my squarespace repo. After pushing, I started my server,  signed in to squarespace locally,  and then my server shuts down and give me this :

```
$ sqs server
> sqs-server: Server.port: 5050

/Users/coolamelin/npm/lib/node_modules/node-squarespace-server/node_modules/node-squarespace-jsont/lib/jsontemplate.js:768
    throw {
    ^
TemplateSyntaxError: Got too few {end} statements

```

before i clear the cache, if i start my server:

```
$ sqs server
undefined:0


SyntaxError: Unexpected end of input
    at Object.parse (native)
    at /Users/coolamelin/npm/lib/node_modules/node-squarespace-server/squarespace-util.js:98:22
    at /Users/coolamelin/npm/lib/node_modules/node-squarespace-server/squarespace-util.js:85:17
    at fs.js:336:14
    at FSReqWrap.oncomplete (fs.js:99:15)
```

then $sqs buster lets me do it all over again. 

Ive reinstalled and updated npm, node not sure what else to try!

im cloning a file which is running fine on squarespace so there should be nothing in the code thats breaking, the only file ive touched is : 

<h4>temple.conf:

```

{

  "name" : "Pacific",
  "author" : "Squarespace",

  "layouts" : {
    "default" : {
      "name" : "Default",
      "regions" : [ "site" ]
    }
  },

  "navigations" : [ {
      "title" : "Main Navigation",
      "name" : "mainNav"
  },
  {
      "title" : "Secondary Navigation",
      "name" : "secondaryNav"
  }],

  "stylesheets" : [
    "tweak.less",
    "helpers.less",
    "mixins.less",
    "base.less",
    "blog.less",
    "index.less",
    "mobile.less"
  ],

  "systemCollections" : [
    "products",
    "gallery",
    "events",
    "album"
  ],

  "server": {
    "siteurl": "https://harrison-brome.squarespace.com",
    "sandbox": true
  }

}

```

Any help helps :)

**Comment by kitajchuk** [comment]
It seems like you may have some json-t that isn't closed properly with the {.end} tag. Look into that for starters and see if you missed one somewhere.

**Comment by kweestian** [comment]
yes of course i was! such a clown 
all good now was just missing a stupid {.end}

thank u for your prompt reply!

**Comment by kitajchuk** [comment]
No problem, glad you're cruising again!
