### ISSUE TITLE
WIDGET ERROR - Access Denied: Invalid session crumb

### ISSUE THREAD

**Issue by Kunamatata** [kitajchuk/node-squarespace-server#103]
Hi,

After launching the sqs server with sandbox: true, since I'm currently on trial account I get this error in the terminal.
I am using <squarespace:block-fields> as well in my template and they don't show up as they would in the squarespace online editor. There isn't the content inside of those custom blocks and their css isn't as shown on the online editor.

> sqs-middleware: WIDGET ERROR - Access Denied:  Invalid session crumb
> sqs-server: Server.error: Access Denied:  Invalid session crumb

Thanks in advance,
Max

**Comment by kitajchuk** [comment]
Skim through this issue thread, but it looks like the server may no longer work on sandbox accounts. Likely a change on Squarespace's end and could be due to security:

https://github.com/kitajchuk/node-squarespace-server/issues/101#issuecomment-113829240

**Comment by kitajchuk** [comment]
@Kunamatata - Are you still getting this issue after busting your cache and restarting the server?

**Comment by kitajchuk** [comment]
@Kunamatata Pretty curious if this is still an issue. This is the only account of this happening so far.

**Comment by Kunamatata** [comment]
@kitajchuk The issue was fixed after paying. Sandbox doesn't work currectly apparently. Sorry for the delayed answer sir!

**Comment by kitajchuk** [comment]
@Kunamatata Sweet, thanks!

**Comment by Kunamatata** [comment]
@kitajchuk Thank you for your this tool and your support!
