### ISSUE TITLE
Sandbox trial mode support

### ISSUE THREAD

**Issue by kitajchuk** [kitajchuk/node-squarespace-server#28]

**Comment by cwaring** [comment]
Great work @kitajchuk, you're right about the TypeKit issue too. In the meantime I've found a workaround is to add `localhost <yoursite>.squarespace.com.local` in your hosts file to trick TypeKit into matching on the domain.

**Comment by kitajchuk** [comment]
Nice! Glad that works for now :)

On Mon, Jan 19, 2015 at 11:19 AM, Chris Waring <notifications@github.com>
wrote:

> Great work @kitajchuk <https://github.com/kitajchuk>, you're right about
> the TypeKit issue too. In the meantime I've found a workaround is to add localhost
> <yoursite>.squarespace.com.local in your hosts file to trick TypeKit into
> matching on the domain.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kitajchuk/node-squarespace-server/issues/28#issuecomment-70545856>
> .
>



-- 
Brandon Lee Kitajchuk
Javascript Junkie
blkpdx.com
