### ISSUE TITLE
{squarespace-headers} output duplicated after opening body tag

### ISSUE THREAD

**Issue by ryananthony** [kitajchuk/node-squarespace-server#59]
This is happening on two different site templates I've pulled down. In the rendered markup, it appears that after the opening body tag, the `{squarespace-headers}` output is being duplicated and seems to inject a comma just before. In the pre-rendered markup, however, the mentioned header output is actually duplicated in the `<head>`.

As you can see from the find-all in Sublime Text, there is only a single reference to this variable in the template folder and it appears before the closing `</head>` tag. I am running the server via Node v0.10.20 inside Git-Bash on Windows 8.1.

![01_sqs-server-injecting-header-elements-after-body-tag](https://cloud.githubusercontent.com/assets/1447940/5635209/f92ebe66-959b-11e4-99c8-b948a65e0ee4.PNG)
![02_single-reference-to-sqs-headers-in-head](https://cloud.githubusercontent.com/assets/1447940/5635211/fdc015ba-959b-11e4-86af-006aa59a9033.PNG)

**Comment by kitajchuk** [comment]
Thanks for noting this. I haven't been able to test on any Windows machines yet so its not too surprising there are some bugs there. I'll try to replicate the setup and see what I can do about fixing this issue :)

**Comment by ryananthony** [comment]
Sorry it took so long to get back to you. The template according to template.conf is "Five" by "Eric E. Anderson".

**Comment by kitajchuk** [comment]
Okay. I'll take a look at that one.

**Comment by kitajchuk** [comment]
I ran the "Five" template stock in VirtualBox on Windows 7 with the latest node and it worked just fine. I'll try the older node version you are running.

**Comment by jarneuyt** [comment]
I have the same issue with the comma. 
I'm using the Base Template (as a developer).

**Comment by jarneuyt** [comment]
Could you check into this issue? 
The problem only seems to happen on your node squarespace server. 
When I push the template online, the problem seems to be gone.

![screen shot 2015-01-28 at 09 47 53](https://cloud.githubusercontent.com/assets/1716614/5934677/cc3489ac-a6d2-11e4-81fe-7914e1a70f8a.png)

**Comment by kitajchuk** [comment]
Yeah, I'm looking into it but haven't been able to reproduce it yet to fix it. What is your setup? Maybe that will help. I replicated @ryananthony setup and didn't get the error :/

**Comment by jarneuyt** [comment]
I'm running your server on Mac OSX (Yosemite) and I'm testing in Chrome.
My developer mode is enabled. The template I started from is the Base Template.

**Comment by kitajchuk** [comment]
@jarneuyt - Okay, so I have to ask if you would mind supplying me with your region file if it doesn't have anything sensitive in it. My setup is Yosemite on Mac, Chrome and an unmodified copy of Base Template in developer/sandbox mode. I still don't get this issue so I'm just unsure what may be causing it.

**Comment by jarneuyt** [comment]
Sure! Here you go: http://cl.ly/42413H46241x
If you need anything else, shoot!

**Comment by jarneuyt** [comment]
I also get this when I check my console:
**"Common running twice .... this is concerning."**

![screen shot 2015-01-28 at 20 12 07](https://cloud.githubusercontent.com/assets/1716614/5944789/fe0e7b34-a729-11e4-8535-8b7970ce9a7c.png)

**Comment by kitajchuk** [comment]
I'll look into that. I wouldn't worry about it since its just your local server. There's still some work to be done on the headers parsing for this project for sure.

**Comment by jarneuyt** [comment]
Ayt! I appreciate your work & time :) Keep it up!

**Comment by kitajchuk** [comment]
Still not replicating the issue. Maybe send me your css/less... There's a known issue in local less compilation vs what is done on the sqs server. I'm wondering if there could be an issue there since the server currently drops the local css inline in the <head>.

**Comment by kitajchuk** [comment]
I meant that to be "in the head element".

**Comment by jarneuyt** [comment]
Hmmm, here you go: http://cl.ly/1L2p3K3V2O3t (my styles folder)

What I did notice is that you added at the top of screen.scss:
'@import "compass";
@import "compass/reset";'

Where does it find that compass and compass/reset?

**Comment by kitajchuk** [comment]
Compass, the command line interface, pulls those in from its installed files. The "compass" import is so you can use Compass' mixins and the reset is a stock reset css include. You don't need to use the reset if you have your own or prefer something else to it.

Also, tested with your css and still cannot replicate the issue :/

**Comment by jarneuyt** [comment]
I uploaded my full project for you.
Hope that will help you out better: http://cl.ly/130Q3Q151b11

**Comment by kitajchuk** [comment]
Ha! I'm working on some updates to the Instrument site and just got this bug replicated locally for that project. I'm looking into a solve for it now.

**Comment by jarneuyt** [comment]
High five! Looking forward to the update.

**Comment by kitajchuk** [comment]
I just merged in the fix for this issue. The latest package version is node-squarespace-server@0.1.18.

**Comment by jarneuyt** [comment]
Thanks! 
Care to share what caused the problem / how you fixed it?

**Comment by kitajchuk** [comment]
The ultimate cause was an incorrect reference to the headers to inject if NOT running a site in sandbox mode.

**Comment by jarneuyt** [comment]
I updated and it looks good now! Rock'n roll! :+1:

**Comment by kitajchuk** [comment]
Sweet! Glad to hear it :D
