### ISSUE TITLE
Page with sub-pages fails to load, see attached error

### ISSUE THREAD

**Issue by joshpopenyc** [kitajchuk/node-squarespace-server#64]
First off- thank you for creating this! Largely, it has been extremely useful.. So kudos to you.

That said, I've hit what appears to be an edge case.

I have a page, which has several subpages (IE, so in the main nav I have a link "about" with a drop-down to subpages, "what we do," "projects," "partners," and "contact.")

All of the subpages load just fine, however if I click the top level link ("About") it throws the below error:
<code>
TypeError: Cannot read property 'typeName' of undefined
   at getTemplateKey (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:286:35)
   at Object.renderTemplate (/usr/local/lib/node_modules/node-squarespace-server/squarespace-template.js:322:23)
   at renderResponse (/usr/local/lib/node_modules/node-squarespace-server/squarespace-server.js:187:21)
   at onExpressRouterGET (/usr/local/lib/node_modules/node-squarespace-server/squarespace-server.js:323:5)
   at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-squarespace-server/node_modules/express/lib/router/layer.js:82:5)
   at next (/usr/local/lib/node_modules/node-squarespace-server/node_modules/express/lib/router/route.js:100:13)
   at Route.dispatch (/usr/local/lib/node_modules/node-squarespace-server/node_modules/express/lib/router/route.js:81:3)
   at Layer.handle [as handle_request] (/usr/local/lib/node_modules/node-squarespace-server/node_modules/express/lib/router/layer.js:82:5)
   at /usr/local/lib/node_modules/node-squarespace-server/node_modules/express/lib/router/index.js:234:24
   at Function.proto.process_params (/usr/local/lib/node_modules/node-squarespace-server/node_modules/express/lib/router/index.js:312:12)
</code>

It should be noted that the link does load just fine when viewing the site in its xxx.squarespace.com url. So it only fails in this case.

I have tried modifying the config file - removing and re-adding both sitewide password and sandbox mode.. (which I have been able to track down other issues I have had to one or both of those attributes).

I'm not sure if this is a problem with my local node setup, an issue with this local server, or a sqs issue  - though I've used grunt and node on other (non sqs sites) without any problem at all on my dev machine.

Any insight here? Is this a known issue or am I that obnoxious edge case that simply hasn't been addressed?

Thanks for the great tool, and thanks in advance for any insight you may have!
-Josh

**Comment by joshpopenyc** [comment]
I should note that no other top level pages/links have errors. However, no other pages have sub-pages.

**Comment by kitajchuk** [comment]
I think I know what you are talking about. I have a question about that. When you load that top level page on the xxx.squarespace.com domain, does it load the first sub-page instead?

I ask because I was playing around with indexes and folders a couple weeks ago and noticed that the top level page for a folder with sub-pages would just load the first sub-page in the tree.

Say I have a folder called `test-folder` and the first sub-page is called `test-page`. When I click test-folder it hits /test-folder/ but immediately redirects to /test-page/. As far as I have tested, indexes work just fine however.

**Comment by kitajchuk** [comment]
In my mind, the solve would be to replicate the redirection that occurs in this scenario on the squarespace.com domains. Seems to make sense.

**Comment by kitajchuk** [comment]
Even with a query string param of format=json on my test site, the /test-folder/ path redirects to /test-page/ with no query string. In testing the node server, the error is throwing because the json is not coming through but rather the html...

**Comment by kitajchuk** [comment]
I fixed the same issue by following suit with how Squarespace seems to be handling root level folder requests. The branch is here, https://github.com/kitajchuk/node-squarespace-server/tree/folder-root-redirect.

If you could go ahead and install that branch locally and test with it that would be great. Let me know if you think its working correctly.

Thanks man!

**Comment by kitajchuk** [comment]
Closing this one out. Merged in the above fix. Published new version node-squarespace-server@0.1.17.
