### ISSUE TITLE
Separate JSON-T into a separate repo

### ISSUE THREAD

**Issue by foleyatwork** [kitajchuk/node-squarespace-server#68]
Hey BK, I was thinking the other day, perhaps we should separate the template engine out into a separate repo. That way we could keep a JS version of JSON-T with all the Squarespace formatters and predicates. You have any thoughts?

**Comment by kitajchuk** [comment]
None other than that's a great idea!

**Comment by kitajchuk** [comment]
I already broke out the middleware, so I think this modular approach to the project is a good idea.

**Comment by foleyatwork** [comment]
Awesome. If/when you feel like breaking it out, let me know. You know the architecture of this server better but I will be ready to contribute as soon as you create the other repo.

**Comment by kitajchuk** [comment]
I guess I would call it either `node-squarespace-template` or `node-squarespace-jsont`. I like the latter.

**Comment by kitajchuk** [comment]
Sounds good man, thanks for the suggestion!

**Comment by foleyatwork** [comment]
You think we could make it so it runs on the client, too? It would be awesome to be able to reuse template code on the server and client.

**Comment by foleyatwork** [comment]
I mean, I know we could. Just bringing it up as a project goal to get your feedback.

**Comment by kitajchuk** [comment]
Yeah, I don't see why we couldn't make it run in both environments.

**Comment by kitajchuk** [comment]
Breaking out the actual json-t lib, predicates and formatters is easy. The harder part is going to be refactoring the code in the squarespace-template.js module. This stuff is pretty gnarly so a good cleanup of it would be nice.

In terms of the client... The project uses the middleware for block and widget rendering which would add an extra layer of complexity to making it work in the browser.

I think I'll spec out the tasks to make it happen and post them.

**Comment by kitajchuk** [comment]
It seems like the middleware would need a client version as well. For that we would have to use jsonp. For instance, this works when you add site and password info as its relevant to your sqs site:

```javascript
$.ajax({
    url: "https://yoursite.squarespace.com",
    data: {
        format: "json",
        password: "yoursitepassword"
    },
    dataType: "jsonp",
    jsonp: "callback"

}).done(function ( res ) {
    console.log( res );
});
```

**Comment by kitajchuk** [comment]
This would work for basic api requests. Block and Widget stuff, idk. The middleware is spoofing headers to make all that work so it would be trial and error to see how far we can get with it.

**Comment by foleyatwork** [comment]
I don't know that we'd have to go that far. When you think about it, you never really need block and widget rendering as a template developer, right? Those will get returned as markup in the {body} or {mainContent} keys.

**Comment by kitajchuk** [comment]
True.

**Comment by kitajchuk** [comment]
I pulled out the json-template code into its own module:
https://github.com/kitajchuk/node-squarespace-jsont

The current published version of the server is now node-squarespace-server@0.1.20.

Any recommendations on the client-side implementation for json-template? It's just a node template engine right now. I figure since you develop templates you would best know how you would like to use it :)
