### ISSUE TITLE
Internal Error: Unable to parse server response from (/api/template/GetTemplateSchema) as JSON.

### ISSUE THREAD

**Issue by jarneuyt** [kitajchuk/node-squarespace-server#74]
I keep getting this error when I work on my localhost. I tried to start from scratch, but still the same error pops up. It started all of a sudden and won't go away now. Any ideas?

![screen shot 2015-02-08 at 15 30 48](https://cloud.githubusercontent.com/assets/1716614/6096882/791bb096-afa7-11e4-945a-be2561fa2789.png)

![screen shot 2015-02-08 at 15 29 40](https://cloud.githubusercontent.com/assets/1716614/6096878/58c9e5d8-afa7-11e4-91be-e6639204d621.png)

**Comment by beaucharman** [comment]
I am getting the same error here

**Comment by cwaring** [comment]
Same here, trying to track it down further. Anyone found a fix/workaround?

**Comment by sonnyhh** [comment]
Yeah, same problem here, and not managed a fix.

**Comment by kitajchuk** [comment]
The server currently prevents calls to /api. This isn't necessarily to say that is the right thing for it to do. For instance, it re-routes any calls to /universal so perhaps a similar approach should be implemented here. Which templates are you guys using?

**Comment by jarneuyt** [comment]
I'm using the base template. (starting from scratch)

**Comment by kitajchuk** [comment]
Alright, I can replicate this locally myself. Interesting, I haven't seen a template make that api request yet. As of last week, my local base-template worked fine with the server. I'm going to try to work this out. I'll post here with any feedback and updates on it :)

**Comment by cwaring** [comment]
Thanks @kitajchuk, if it helps any here's a stacktrace from the minified Squarespace JS
![screen shot 2015-02-09 at 19 41 42](https://cloud.githubusercontent.com/assets/106938/6112908/bd5d0858-b093-11e4-8a55-36551bfc2cd0.png)

**Comment by kitajchuk** [comment]
Yeah, it looks like I just need to just let those requests go through so any Squarespace YUI code executing can receive the data it needs.

**Comment by kitajchuk** [comment]
Just merged a fix for this issue, 42bea74f2b82dc6a5decd8ababbab36f5e7f6da0. Tested with Base Template. New package is node-squarespace-server@0.1.23.

**Comment by cwaring** [comment]
:+1:
