### ISSUE TITLE
Double output

### ISSUE THREAD

**Issue by jarneuyt** [kitajchuk/node-squarespace-server#77]
My page gets shown twice (see screenshot). I tried to reproduce the bug with a very simple file and still the same issue. Any idea what this could be? 
*Note: when i update my home.region, the top part updates, while the second part (duplicated?) doesn't change.*

![screen shot 2015-02-10 at 10 38 50](https://cloud.githubusercontent.com/assets/1716614/6124830/171cf6be-b111-11e4-8d3a-fd733caeebfd.png)

![screen shot 2015-02-10 at 10 43 08](https://cloud.githubusercontent.com/assets/1716614/6124922/aca72b64-b111-11e4-8402-a1bd8c863bf3.png)

**Comment by cwaring** [comment]
I'm getting the same issue too, it seems to render the local templates then load in the current public squarespace html (and headers) at the bottom of the document.

**Comment by cwaring** [comment]
I've tracked it down to the {squarespace-footers} tag, removing this fixes the duplicate output for me.

**Comment by jarneuyt** [comment]
Good find. I'm also having issues again with the caching. 
@kitajchuk You resolved the caching problem, no? The issue seems to be back.

**Comment by jarneuyt** [comment]
Good find @cwaring.
The double output seems to be "overriding" your current css. So the online site.css interferes with your local css. Pretty annoying. When I remove the squarespace-footers tag, I don't seem to have any problems anymore :)

**Comment by sonnyhh** [comment]
Having the same issues here with the double output... Can replicate the temporary fix by removing the {squarespace-footers} tag also. Any thoughts on a fix?

**Comment by kitajchuk** [comment]
What version of the server are you guys on?

**Comment by jarneuyt** [comment]
The latest.

**Comment by kitajchuk** [comment]
Okay, I'll take a look.

**Comment by kitajchuk** [comment]
Replicated this locally. Looking into a fix.

**Comment by kitajchuk** [comment]
Looks like they changed the imageloader code snippet, so the footers parsing is breaking. Unfortunately there's not a better way to do that so I'll just have to update the code. Funny enough, they spelled "bootstrapper" wrong, "imageloader-bootstraper".

**Comment by kitajchuk** [comment]
Just merged a fix in for this issue, 06282425c3ca45bb8ad0abc9c1dbc8a7b22a730b. The latest package version is node-squarespace-server@0.1.24. If this seems to work then I'll close this issue :)

**Comment by cwaring** [comment]
Ha, great. Least we know where to look when everything explodes again if they fix the typo :)

Thanks for the patch :+1:

**Comment by beaucharman** [comment]
Thank you @kitajchuk !
