### ISSUE TITLE
No content is being returned in my template.

### ISSUE THREAD

**Issue by loadedsith** [kitajchuk/node-squarespace-server#83]
The title is updating, but the content I add to SquareSpace is not being added to the local site. I looked in the sqs-cache for my content, and the data includes my video and gallery, but it's not added to the page.

I am using a sandbox account, and I get no errors from the server. If you could point me in the right direction? Thanks

**Comment by kitajchuk** [comment]
If you add content in the CMS, you have to bust your local cache manually. Either stop the server and run `sqs buster` or use the `?nocache` query string parameter on the page. Let me know if that helps.

**Comment by loadedsith** [comment]
It does not. It does seem to work to a degree, the site title changes, and the color of the page seems to have changed. The content is configured as pages under the welcome page.

**Comment by loadedsith** [comment]
When I changed the background color from black, it seems there's a message "You must select a collection to display."

**Comment by kitajchuk** [comment]
Hmm, what template are you using? Also, any more specifics? The more info I have the better I can help troubleshoot what may be happening.

**Comment by loadedsith** [comment]
I can appreciate that, I wish better knew what to provide. The theme is "Pacific".

**Comment by kitajchuk** [comment]
That's a starting point. How much have you changed on it so far?

**Comment by kitajchuk** [comment]
Also, even though it sounds like these aren't your issues, it may help to check this section of the readme out just in case: https://github.com/kitajchuk/node-squarespace-server#troubleshooting

**Comment by loadedsith** [comment]
Not much, content, and a little css

**Comment by loadedsith** [comment]
https: Check
"sandbox:true" in template.conf > server: Check
Cache buster tried: Check

**Comment by loadedsith** [comment]
there's a hyphen in my user name, could that be related?

**Comment by kitajchuk** [comment]
I don't think so. As long as you are logging in fine locally that wouldn't be an issue. I just spun up a site using that template and have it running locally with what appears to be your issue: no content. This is also causing a Javascript error to be thrown locally in site.js. I'll dig around and see if I can resolve this problem.

**Comment by kitajchuk** [comment]
Good news. It appears the problem is in the use of this predicate: `{collectionTypeNameEquals? type}`. I haven't run into this one yet and as far as I know, its not in the public docs. This resolve will actually require an update to https://github.com/kitajchuk/node-squarespace-jsont. Once that is published you can reinstall the server with npm and you should be clear on this issue. I'll let you know when this is ready.

**Comment by loadedsith** [comment]
Thanks for the effort!

**Comment by kitajchuk** [comment]
I published the changes. The new version of the server:
node-squarespace-server@0.1.28

And the version of jsont it should be pulling is:
node-squarespace-jsont@0.1.5

Let me know if that helps. I would run `sqs buster` after updating your server install with npm just to start fresh again.

**Comment by loadedsith** [comment]
Success! Thanks so much! For the record, my update command failed, so I

     npm remove -g node-squarespace-server

then

     npm install -g node-squarespace-server

then

     sqs buster

then

     sqs server

Logged in, and watched your beautiful code render my site. Thanks! Id gladly buy you a beer, anytime.

**Comment by kitajchuk** [comment]
Awesome! Glad we figured it out :)
