### ISSUE TITLE
Problems with "Momentum" template

### ISSUE THREAD

**Issue by skrichten** [kitajchuk/node-squarespace-server#95]
I'm trying to use your local server to modify the "Momentum" template but it seems that something about the template configuration is tripping up this local server.  The photo gallery link in the main navigation doesn't get an href and the photos in the gallery do not render.

The photogallery is a custom "index" type collection with this configuration...
{
  "title" : "Index",
  "folder": true,
  "fullData": true,
  "acceptTypes" : ["gallery"],
  "addText": "Add Project",
  "icon": "projects",
  "index" : true
}

The config of the accepted "gallery" type looks like this...

{
  "title" : "Gallery",
  "ordering" : "user-orderable",
  "pageSize" : 9999,
  "addText" : "Add Images or Video",
  "icon" : "gallery",
  "acceptTypes" : [ "image", "video" ]
}

I think the local server code is handling things different than squarespace when a collection is configured as a both a folder and an index.  Any ideas about what the problem is?

**Comment by kitajchuk** [comment]
Offhand, I'm not positive. I'll have to play around with it to see what is breaking down.

**Comment by skrichten** [comment]
Thanks.  I'm still not sure what's up with the link in the main navigation, but I figured out the issues with the gallery itself.  It looks like the local server does not support "or" logic like this... {.if title || body}.  And the other issue seems to be lack of support for the predicate {.image?} which isn't surprising since I could not find it in the squarespace docs either.

**Comment by kitajchuk** [comment]
Ah, yeah. The "or" operator isn't working for the local server. The Squarespace guys are now working on making what should be the real deal version of this tool, so there's that to look forward to. It will be able to interface with the real production code for Squarespace thus being a better tool in general. As for the JSON-T stuff, they are working on a direct port of their Java version into Javascript. Ideally that means it would be maintained at the same rate as the production Java version. I'm not sure when all this will come to fruition, but you can hit up @foleyatwork who knows more about it :)

**Comment by kitajchuk** [comment]
Going to close this issue and open one directly related to the "or" logic support with if conditions.
