### ISSUE TITLE
Support for static pages?

### ISSUE THREAD

**Issue by skrichten** [kitajchuk/node-squarespace-server#96]
It looks like this server does not support static pages as described here...

http://developers.squarespace.com/template-overview-1/?rq=.page
Under the section called "/pages/"

Is this something that could be added?

**Comment by kitajchuk** [comment]
Most likely, yes. I just haven't looked into it as of yet.

**Comment by okalex** [comment]
This appears to be due to the fact that Squarespace does not include the `mainContent` field in the json data for these pages. The server would need to make a separate request to the same url with `?format=main-content` to retrieve this data. I'm not sure if it'd be better to do this here or in the `getJson` function of [node-squarespace-middleware](https://github.com/kitajchuk/node-squarespace-middleware).

**Comment by kitajchuk** [comment]
This would definitely be handled in the server as opposed to the middleware. The condition would be applied for static pages and that extra request would have to go through the middleware to retrieve the data.

**Comment by kitajchuk** [comment]
My understanding after reading up a bit is that static pages don't have mainContent. You can't add it in the CMS. Seems like the only options are high-level page settings and choosing which layout you want the page to render through.

**Comment by kitajchuk** [comment]
Well, it just so happens we have found a good use for static pages on a current project, so this became a priority for me. This commit: 87ddf1e1cc0f3d4f60da33fddce9dc5f41f934e4 is the static page support implementation. It's working for me now on the project. I have a static page set as my homepage and spun up some tests that work as well. I'm curious to see if naming conventions would breakdown the implementation in anyway, so updating your server @skrichten and @okalex and testing it out would be rad. If you find any hiccups with it, feel free to open this issue back up and keep the convo going.

And of course, to update: `npm update -g node-squarespace-server`.

Thanks guys!

**Comment by zacharyz** [comment]
Hey @kitajchuk I just tried it out, and it at least loaded up the static page. We include some partials though via 
```
{@|apply navigation.block}
```
 that did not render correctly though and instead display "false."

**Comment by kitajchuk** [comment]
Oh snap, I guess I excluded .page files from all the other template parsing. I can make sure that happens and try again.

**Comment by kitajchuk** [comment]
Okay, @zacharyz, this commit here - ba758d759d8b86279aeb168f04f1f4b48db6a731 - adds static pages to the block partial replacements. Let me know if that works for you when you update and try again. I would run an `sqs buster` before testing.

**Comment by kitajchuk** [comment]
@zacharyz - Re-open this issue if you still get issues. Hopefully this last merge resolved them all though :)

**Comment by zacharyz** [comment]
@kitajchuk :+1: thanks!

**Comment by kitajchuk** [comment]
Forgot to publish last night, just did. Latest is 0.2.12 on NPM which also includes the folder-navigation support.

**Comment by okalex** [comment]
Thanks, @kitajchuk! I'll buy you a beer if I see you around town ;)
